import { MenuItem, TraiteurPackage, Review } from './types';

export const RESTAURANT_INFO = {
  name: "KHADY'S FOOD & EVENT",
  shortName: "Khady's",
  slogan: "L'excellence de la gastronomie africaine & Service Traiteur d'exception",
  city: "Niamey, Niger",
  address: "Boulevard Mali Béro, Quartier Plateau, Niamey",
  phone: "+227 74 44 16 21",
  whatsappNumber: "22774441621",
  openingHours: "Tous les jours : 11h30 - 23h30",
  currency: "FCFA",
  deliveryDistricts: [
    { name: "Plateau", fee: 1000 },
    { name: "Koira Kano", fee: 1500 },
    { name: "Yantala", fee: 1500 },
    { name: "Harobanda", fee: 2000 },
    { name: "Recasement", fee: 1500 },
    { name: "Bobiel", fee: 2000 },
    { name: "Francophonie", fee: 1500 },
    { name: "Goudel", fee: 2000 },
    { name: "Dar-es-Salam", fee: 2000 },
    { name: "Autre quartier de Niamey", fee: 2500 }
  ]
};

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: "item-doukounou-khady",
    name: "LE FAMEUX DOUKOUNOU DE KHADY",
    description: "Le fameux Doukounou traditionnel de Khady : beignets de maïs fermenté moelleux à la vapeur, servis avec gros poisson capitaine braisé croustillant, sauce tomate mijotée, piment maison et oignons frais.",
    price: 3000,
    category: "plats",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Plat Vedette",
    preparationTime: "20 min",
    spicyLevel: 2,
    ingredients: ["Doukounou maïs vapeur", "Poisson capitaine braisé", "Sauce tomate épicée Khady", "Oignons émincés"],
    available: true,
    createdAt: "2026-01-09T12:00:00Z"
  },
  {
    id: "item-bowl-complet",
    name: "BOWL COMPLET SAHEL",
    description: "Salade fraîcheur sahélienne complète : poulet grillé effiloché, maïs doux, concombres croquants, tomates cerises, avocat et vinaigrette maison aux herbes.",
    price: 3500,
    category: "entrees",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Fraîcheur",
    preparationTime: "15 min",
    spicyLevel: 1,
    ingredients: ["Poulet grillé", "Salade croquante", "Avocat", "Maïs doux", "Concombre"],
    available: true,
    createdAt: "2026-01-09T13:00:00Z"
  },
  {
    id: "item-thieb-rouge",
    name: "Thiéboudienne Penda Royal (Riz Rouge)",
    description: "Le chef-d'œuvre sénégalais par Khady : riz rouge parfumé mijoté au bouillon de mérou frais, légumes du jardin (chou, carotte, manioc, aubergine), piment doux et bissap blanc acidulé.",
    price: 4500,
    category: "plats",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Plat Signature",
    preparationTime: "25-35 min",
    spicyLevel: 2,
    ingredients: ["Mérou frais", "Riz cassé parfumé", "Légumes mijotés", "Bouillon secret Khady", "Bissap blanc"],
    available: true,
    createdAt: "2026-01-10T12:00:00Z"
  },
  {
    id: "item-dibi-agneau",
    name: "Dibi d'Agneau Grillé au Feu de Bois",
    description: "Morceaux tendres d'agneau grillés à la minute au feu de bois selon la pure tradition de Niamey, assaisonnés au mélange d'épices Kankankan piquant, oignons croquants et moutarde à l'ancienne.",
    price: 5500,
    category: "plats",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Incontournable",
    preparationTime: "30-40 min",
    spicyLevel: 2,
    ingredients: ["Agneau local frais de Niamey", "Épices Kankankan", "Oignons émincés", "Moutarde douce"],
    available: true,
    createdAt: "2026-01-11T12:00:00Z"
  },
  {
    id: "item-yassa-poulet",
    name: "Yassa Poulet Fermier Braisé",
    description: "Poulet fermier doré au feu de braise, nappé d'une généreuse sauce onctueuse aux oignons caramélisés, moutarde de Dijon, jus de citron vert pressé et olives vertes. Servi avec riz blanc parfumé.",
    price: 4000,
    category: "plats",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Coup de Cœur",
    preparationTime: "25 min",
    spicyLevel: 1,
    ingredients: ["Poulet fermier", "Oignons caramélisés", "Citron vert", "Olives", "Riz jasmin"],
    available: true,
    createdAt: "2026-01-12T12:00:00Z"
  },
  {
    id: "item-mafe-boeuf",
    name: "Mafé de Bœuf Gourmand",
    description: "Viande de bœuf ultra fondante mijotée longuement dans une sauce arachide dorée riche et parfumée, carottes fondantes et patates douces de saison. Servi avec riz blanc chaud.",
    price: 4000,
    category: "plats",
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Classique d'Or",
    preparationTime: "20 min",
    spicyLevel: 1,
    ingredients: ["Bœuf tendre", "Pâte d'arachide torréfiée", "Patate douce", "Carottes", "Riz"],
    available: true,
    createdAt: "2026-01-13T12:00:00Z"
  },
  {
    id: "item-riz-gras-poulet",
    name: "Riz Gras Sahélien au Poulet Bicyclette",
    description: "Riz parfumé cuit dans un savoureux fond de volaille tomaté et épicé, accompagné d'un quart de poulet bicyclette croustillant et de rondelles de bananes plantain dorées.",
    price: 3800,
    category: "plats",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    isPopular: false,
    isFeatured: true,
    badge: "Spécialité Sahel",
    preparationTime: "25 min",
    spicyLevel: 1,
    ingredients: ["Poulet bicyclette local", "Riz gras parfumé", "Tomate fraîche", "Alloco"],
    available: true,
    createdAt: "2026-01-14T12:00:00Z"
  },
  {
    id: "item-pastels-poisson",
    name: "Pastels Croustillants au Poisson (10 pcs)",
    description: "Petits chaussons dorés et croustillants farcis d'une farce savoureuse de poisson noble effiloché, herbes fraîches et aromates. Accompagnés de la fameuse sauce tomate épicée Khady's.",
    price: 2500,
    category: "entrees",
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Top Apéro",
    preparationTime: "15 min",
    spicyLevel: 1,
    ingredients: ["Pâte maison croustillante", "Farce de poisson", "Sauce tomate épicée Khady"],
    available: true,
    createdAt: "2026-01-15T12:00:00Z"
  },
  {
    id: "item-alloco-piment",
    name: "Alloco Doré & Sauce Piment Vert Maison",
    description: "Bananes plantains mûres frites à point, dorées et fondantes à cœur, servies avec notre célèbre pot de piment vert Khady préparé à la main.",
    price: 1500,
    category: "entrees",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: false,
    badge: "Incontournable",
    preparationTime: "15 min",
    spicyLevel: 2,
    ingredients: ["Banane plantain mûre", "Sel de mer", "Piment vert Khady"],
    available: true,
    createdAt: "2026-01-16T12:00:00Z"
  },
  {
    id: "item-box-sauces-trio",
    name: "Box Signature 'Les 3 Sauces Khady'",
    description: "La coffret cadeau ou maison réunissant nos 3 recettes secrètes en bocaux en verre stérilisés (3x350g) : Sauce Yassa mijotée aux oignons, Sauce Mafé cacahuète dorée et Pâte de Piment Khady.",
    price: 8500,
    category: "sauces",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: true,
    badge: "Box Cuisinez Chez Vous",
    preparationTime: "Disponible de suite",
    spicyLevel: 1,
    ingredients: ["Sauce Yassa", "Sauce Mafé", "Pâte Piment Vert Khady"],
    available: true,
    createdAt: "2026-01-17T12:00:00Z"
  },
  {
    id: "item-sauce-yassa-pot",
    name: "Bocal Sauce Yassa Authentique (500ml)",
    description: "Bocal prêt à l'emploi de sauce Yassa mijotée artisanalement à Niamey. Ajoutez simplement votre poulet ou poisson poêlé pour un repas digne d'un grand restaurant en 10 minutes !",
    price: 3200,
    category: "sauces",
    image: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=800&q=80",
    isPopular: false,
    isFeatured: false,
    badge: "Prêt en 10 min",
    preparationTime: "Disponible de suite",
    spicyLevel: 1,
    ingredients: ["Oignons caramélisés", "Moutarde", "Citron vert", "Aromates"],
    available: true,
    createdAt: "2026-01-18T12:00:00Z"
  },
  {
    id: "item-sauce-piment-vert",
    name: "Pot de Piment Vert Habanero Khady (200ml)",
    description: "La touche piquante irrésistible qui fait la réputation de nos plats. Préparé avec des piments frais sélectionnés, ail, gingembre et pointe de citron.",
    price: 1800,
    category: "sauces",
    image: "https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: false,
    badge: "Explosion de Saveurs",
    preparationTime: "Disponible de suite",
    spicyLevel: 3,
    ingredients: ["Piment vert frais de Niamey", "Ail", "Gingembre", "Huile d'olive"],
    available: true,
    createdAt: "2026-01-19T12:00:00Z"
  },
  {
    id: "item-jus-bissap",
    name: "Jus de Bissap Maison Menthe Fraîche (50cl)",
    description: "Infusion de fleurs d'hibiscus sélectionnées, parfumée à la menthe fraîche du jardin et délicatement sucrée. Servi très frais.",
    price: 1000,
    category: "boissons",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: false,
    badge: "100% Naturel",
    preparationTime: "Frais & Glacé",
    spicyLevel: 0,
    ingredients: ["Fleurs d'hibiscus", "Menthe fraîche", "Sucre de canne", "Fleur d'oranger"],
    available: true,
    createdAt: "2026-01-20T12:00:00Z"
  },
  {
    id: "item-jus-bouye",
    name: "Jus de Bouye Crémeux (Pain de Singe - 50cl)",
    description: "Le nectar royal de pulpe de baobab onctueux, riche en vitamine C, parfumé à la vanille de Madagascar et une touche de lait condensé.",
    price: 1200,
    category: "boissons",
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80",
    isPopular: true,
    isFeatured: false,
    badge: "Énergie & Douceur",
    preparationTime: "Frais & Glacé",
    spicyLevel: 0,
    ingredients: ["Pulpe de fruit du baobab", "Vanille", "Lait doux", "Sucre"],
    available: true,
    createdAt: "2026-01-21T12:00:00Z"
  }
];

export const TRAITEUR_PACKAGES: TraiteurPackage[] = [
  {
    id: "pkg-mariage-royal",
    title: "Formule Mariage & Célébration Royale",
    tagline: "L'art de recevoir avec prestige à Niamey",
    pricePerPerson: 7500,
    minGuests: 30,
    popular: true,
    features: [
      "Buffet chaud prestige (Thiéboudienne Royal, Dibi d'Agneau, Poulet Yassa)",
      "Assortiment d'entrées (Pastels poisson, Alloco, Brochettes Tchoukoutou)",
      "Bar à jus naturels artisanaux à volonté (Bissap, Bouye, Gingembre)",
      "Dressage élégant, chafing dishes et service à table par l'équipe Khady",
      "Dégustation préalable offerte pour 2 personnes"
    ],
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "pkg-seminaire-pro",
    title: "Formule Séminaire & Déjeuner d'Entreprise",
    tagline: "Des pauses gourmandes raffinées pour vos équipes et délégations",
    pricePerPerson: 5000,
    minGuests: 15,
    features: [
      "Plat chaud au choix servi en barquettes individuelles hermétiques de luxe",
      "Entrée fraîche + Pastel croustillant",
      "Boisson naturelle 33cl au choix",
      "Livraison ponctuelle garantie avec facturation professionnelle à Niamey"
    ],
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "pkg-bapteme-famille",
    title: "Formule Fête de Famille & Baptême",
    tagline: "Convivialité, générosité et saveurs authentiques",
    pricePerPerson: 6000,
    minGuests: 20,
    features: [
      "Grand plat traditionnel au choix (Riz rouge ou Mafé)",
      "Marmite spéciale de Dibi grillé garni",
      "Grands pichets de Bissap glacé et jus de Bouye",
      "Option mise à disposition de vaisselle et serveurs"
    ],
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80"
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    author: "Aminata Ousseini",
    rating: 5,
    comment: "Le meilleur Thiéboudienne de tout Niamey sans hésitation ! Le riz a exactement le goût traditionnel de Dakar, et le mérou était fondant. Livraison ultra rapide au Plateau !",
    date: "Il y a 2 jours",
    dishName: "Thiéboudienne Penda Royal",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    verified: true
  },
  {
    id: "rev-2",
    author: "Dr. Ibrahim Mahamadou",
    rating: 5,
    comment: "Nous avons fait appel à Khady's Event pour notre cocktail de fin d'année (80 personnes). Les invités parlent encore du Dibi d'agneau et des pastels ! Service impeccable.",
    date: "Il y a 5 jours",
    dishName: "Service Traiteur Entreprise",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    verified: true
  },
  {
    id: "rev-3",
    author: "Fatimata B.",
    rating: 5,
    comment: "J'ai acheté la Box 3 Sauces pour ma maison à Koira Kano. C'est magique : en 15 minutes j'ai fait un Yassa aussi bon qu'au restaurant !",
    date: "Il y a 1 semaine",
    dishName: "Box Signature 'Les 3 Sauces'",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    verified: true
  }
];
